[2024-08-01T20:17:08.721+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline2.reddit_extraction manual__2024-08-01T20:17:07.447214+00:00 [queued]>
[2024-08-01T20:17:08.733+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline2.reddit_extraction manual__2024-08-01T20:17:07.447214+00:00 [queued]>
[2024-08-01T20:17:08.734+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-08-01T20:17:08.749+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-08-01 20:17:07.447214+00:00
[2024-08-01T20:17:08.755+0000] {standard_task_runner.py:57} INFO - Started process 1272 to run task
[2024-08-01T20:17:08.758+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline2', 'reddit_extraction', 'manual__2024-08-01T20:17:07.447214+00:00', '--job-id', '627', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpn1tgwqym']
[2024-08-01T20:17:08.759+0000] {standard_task_runner.py:85} INFO - Job 627: Subtask reddit_extraction
[2024-08-01T20:17:08.815+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline2.reddit_extraction manual__2024-08-01T20:17:07.447214+00:00 [running]> on host 8eab068d030e
[2024-08-01T20:17:08.905+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline2' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T20:17:07.447214+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T20:17:07.447214+00:00'
[2024-08-01T20:17:08.909+0000] {logging_mixin.py:151} INFO - connected to reddit!
[2024-08-01T20:17:08.910+0000] {logging_mixin.py:151} INFO - <praw.models.listing.generator.ListingGenerator object at 0x7f4bf85e5430>
[2024-08-01T20:17:09.335+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_dag.py", line 50, in reddit_pipeline
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 59, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
[2024-08-01T20:17:09.348+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline2, task_id=reddit_extraction, execution_date=20240801T201707, start_date=20240801T201708, end_date=20240801T201709
[2024-08-01T20:17:09.361+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 627 for task reddit_extraction (received 401 HTTP response; 1272)
[2024-08-01T20:17:09.372+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-01T20:17:09.395+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
